name: Auto Commit README

on:
  push:
    paths:
      - "README.md"
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  commit-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we get all history

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check for changes
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes detected. Skipping commit."
            exit 0
          fi

      - name: Commit & Push Changes
        run: |
          git pull origin main --rebase  # Avoid merge conflicts
          git add README.md
          git commit -m "Auto commit README changes [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
